[params.homeInfoParams]
Content = ""
Title = "### Easy Hugo Management – Anytime, Anywhere."


# ---------菜单部分-------
[[menu.main]]
identifier = "posts"
name = "Download"
url = "https://github.com/Easy-Hugo/release/releases"
weight = 10

[[menu.main]]
identifier = "series"
name = "QuickStart"
url = "/posts/quick-start/"
weight = 30

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 40


[[menu.main]]
name = "Search"
url = "/search/"
weight = 50
