[params.homeInfoParams]
Content = ""
Title = "### Easy Hugo Management – Anytime, Anywhere."


# ---------菜单部分-------
[[menu.main]]
identifier = "posts"
name = "Download"
url = "/posts/change-log/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 40

[[menu.main]]
name = "Search"
url = "/search/"
weight = 50
